### ISSUE TITLE
Corregir sistema inicial de puntos

### ISSUE THREAD

**Issue by csagastegui59** [Waldochrf/hello-world#1]
Cuando se inicia la aplicación directamente me muestra el mensaje de que tengo "x" cantidad de puntos, sugiero que agregues un texto antes para explicar al usuario que se le asignará un puntaje random para empezar y así sea entendible.

![Screenshot from 2022-09-14 00-19-01](https://user-images.githubusercontent.com/45051315/190065794-8bda401e-9d97-4eca-9c5d-4ccf3060d72e.png)

**Comment by Waldochrf** [comment]
Buenas Tardes se realizo lo solicitado.
![image](https://user-images.githubusercontent.com/113267814/190712518-2c31644f-8492-4cca-b187-350696393b32.png)
