### ISSUE TITLE
Agregar validación de nombre

### ISSUE THREAD

**Issue by csagastegui59** [Waldochrf/hello-world#2]
Al momento de ingresar mi nombre me permite ingresar cualquier caracter o incluso solo presionar la tecla Enter sin ingresar nada y me acepta, sugiero agregar validaciones para que el nombre solo acepte letras y no acepte un string vacío.

![Screenshot from 2022-09-14 00-22-43](https://user-images.githubusercontent.com/45051315/190066218-4e14dafc-b012-4ade-9c7b-b37d5e2bc4d0.png)

![Screenshot from 2022-09-14 00-23-36](https://user-images.githubusercontent.com/45051315/190066404-5119c7b4-e486-40aa-88a3-c83eaf337ab2.png)

**Comment by Waldochrf** [comment]
Se agrego validacion:

![image](https://user-images.githubusercontent.com/113267814/190873099-5294d7ec-f918-4b0b-a445-c990d6d185bc.png)

![image](https://user-images.githubusercontent.com/113267814/190873130-253f734a-8c57-4791-9244-986b4ce9453d.png)
