### ISSUE TITLE
Mejorar el case sensitive

### ISSUE THREAD

**Issue by csagastegui59** [Waldochrf/hello-world#3]
Cuando ingreso las alternativas A,B,C o D en mayúsculas sugiero que el programa convierta el input del usuario en minúsculas, se podría usar el método .lower() en el input.

![Screenshot from 2022-09-14 00-26-22](https://user-images.githubusercontent.com/45051315/190066675-d7361c2c-281d-4f2e-979b-f596fe8a5ea7.png)

**Comment by Waldochrf** [comment]
Se añadió el punto .lower() para que las mayúsculas se conviertan en minúsculas.

![image](https://user-images.githubusercontent.com/113267814/190829659-b794814d-2d8b-413a-ae21-7abe987ca019.png)
