### ISSUE TITLE
Arreglar contador de preguntas

### ISSUE THREAD

**Issue by csagastegui59** [Waldochrf/hello-world#4]
Luego de haber respondido la primera pregunta, muestra la siguiente pero el número de pregunta sigue siendo el número 1)

Primera pregunta:
1) ¿Como se llama el protagonista de one piece?
Segunda pregunta:
1) ¿Cual es la fruta preferida de Nami?
Tercera pregunta:
1) ¿Cual fue la primera katana de Zoro Roronoa?

Es decir, cambiar el contador "1)" para que muestre "1)"  "2)" "3)" según el número de pregunta

![Screenshot from 2022-09-14 00-28-55](https://user-images.githubusercontent.com/45051315/190067012-1e674083-b7c0-43c8-867e-0a0e81618da6.png)

**Comment by Waldochrf** [comment]
Se arreglo los contadores solicitados.

![image](https://user-images.githubusercontent.com/113267814/190829308-d357c8d2-4025-4752-880d-cf8e12504b3b.png)
