### ISSUE TITLE
Error con sistema de puntuación

### ISSUE THREAD

**Issue by csagastegui59** [Waldochrf/hello-world#5]
Si la primera pregunta se responde de manera errónea, esto nos da un puntaje negativo, si las siguientes preguntas se responden de manera correcta el score se multiplica y me da un score negativo más alto aún, en lugar de aumentar mi puntaje.

![Screenshot from 2022-09-14 00-33-25](https://user-images.githubusercontent.com/45051315/190067817-8de81e0f-cd2a-42dd-a971-5ebeff25f173.png)

**Comment by Waldochrf** [comment]
Se corrigió lo solicitado.
![image](https://user-images.githubusercontent.com/113267814/190828937-51378b8f-e475-417d-a491-78850b0e1864.png)
