### ISSUE TITLE
Error en despedida al ingresar un nombre vacío 

### ISSUE THREAD

**Issue by csagastegui59** [Waldochrf/hello-world#6]
La despedida del juego al haberlo culminado y colocar cualquier tecla para darlo por terminado, me muestra el mensaje "Espero {nombre} que lo hayas pasado bien, hasta pronto!"
Probablemente es debido a que al momento de ingresar mi nombre al inicio del juego, solo presioné la tecla Enter y se ingresó un string vacío.

![Screenshot from 2022-09-14 00-35-52](https://user-images.githubusercontent.com/45051315/190068159-74ff065e-be22-4a1a-9ce0-b7bb9a360868.png)

**Comment by Waldochrf** [comment]
Se arreglo el error, ahora muestra el nombre del jugador.
![image](https://user-images.githubusercontent.com/113267814/190829087-a84360f0-2670-4cb1-bb18-df33785d20c3.png)
